### ISSUE TITLE
Choose a database to use

### ISSUE THREAD

**Issue by tsmuse** [sfbrigade/stop-violence#24]
As part of [Central index of resources from PDF](https://github.com/sfbrigade/stop-violence/issues/7):
We need to choose a database to use that isn't overkill for this project

**Comment by rjkroege** [comment]
Let's do the simplest thing: SQLite until proven inadequate. And then upgrade to Postgres.

**Comment by tsmuse** [comment]
Sounds good to me, moving this to closed.
