### ISSUE TITLE
WE NEED A NAME!!!!!

### ISSUE THREAD

**Issue by tsmuse** [sfbrigade/stop-violence#28]
We need a name for the project, now that we know that we are building an interactive reference guide. What should we call this thing?

**Comment by bmikol** [comment]
"Reference" doesn't sit well with me, as it leans too close to dictionary-type meanings; if anything, this is a compendium for _referrals_; but abstracting it out a little bit, it's a compilation of _resources_ - from a resource itself (SFWAR). A resource for helping people rise again from a personal tragic event.

Being a bit of a word geek, I looked at the etymology of "resource" and found a delightfully appropriate root:

> from obsolete French _ressourse_, feminine past participle (used as a noun) of Old French dialect _resourdre_ ‘rise again, recover’ (based on Latin _surgere_ ‘to rise’).

…although there seems to be some debate on the Latin root; another etymology site cites _resurgere_ ("rise again") being shared as the root of both "resource" and "resurgent". 

If we stick to this "rise again" theme, one could say it's pretty fitting that this project originates from SF data - given the city's history of "rising again" after catastrophic events. And, what's the most associated image to the concept of "rising again", but the phoenix (used, in fact, by the [2006 centennial celebration of the 1906 earthquake](http://www.examiner.com/article/landmarks-from-the-1906-san-francisco-earthquake-and-fire))?

I'm not inclined to leave it at "phoenix" given the Arizona city, so going down the etymological rabbit hole again, we get:

>Old English and Old French _fenix_, from Medieval Latin _phenix_, from Latin _phoenix_, from Greek _phoinix_

Personally, I'm partial to "fenix" or "phenix" (suffixed by "project"? "app"? something else or nothing at all?); they're concise ancestral words, and actually kinda snazzy in terms of contemporary naming conventions.

**Comment by tsmuse** [comment]
sfsbook.org is the domain name. Project name is SF Safebook? SF Survivorbook?
