### ISSUE TITLE
Initial exploration of SF Open Data 

### ISSUE THREAD

**Issue by tsmuse** [sfbrigade/stop-violence#5]
We are currently unsure if there is any data that is available in the open data that the city has shared at https://data.sfgov.org/  This work will help us create a better set of hypothesis to bring to the data science team to do a more detailed dive into the data.  

We need a set of visualizations that will give us a better idea of what is going on in the data sets that might help us better understand the problem.

**Comment by rjkroege** [comment]
I'll explore this and update. It's a bit open ended so no particular reason for other people to not have a go at this too.

**Comment by rjkroege** [comment]
Breakdown of tasks.

- [ ] Figure out how to automatically download data from the SFOpen site
- [ ] Insert data into a SQL database
- [ ] Histograms: category uniqueness, description clustering, etc.

**Comment by tsmuse** [comment]
Closing this issue for now because we have decided on a direction that doesn't need this data. WIll reopen if we need to dig into the OpenSF data in the future
